version: "3.7"

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 3030:3030
    command: ["yarn", "start:dev"]
    networks:
      - car_park_availability
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 10s
      timeout: 20s
      retries: 5

  web:
    build:
      context: ./web
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - car_park_availability
    ports:
      - 80:80
    depends_on:
      api:
        condition: service_healthy

# volumes:
#   mongo_data:
#   postgres_data:

networks:
  car_park_availability: